# Generated by Django 5.0.6 on 2024-05-26 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mlm', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='referral_code',
            field=models.CharField(default='85E192EB1A', max_length=10, unique=True),
        ),
    ]
